### PR TITLE
Allow SOCKS5 with CurlClient

### PR DESCRIPTION
**Pull request by grepsuzette**
A question is of course that of security.

Assumption: `sys.io.Process()` when second argument is an `Array` is properly sanitized.
=> no checks.

### CODE REVIEW

**Comment by grepsuzette** [comment]
Actually,

> Assumption: sys.io.Process() when second argument is an Array is properly sanitized.

Even without breaking the escape mechanisme, 
there are so many options available, it is actually hard to imagine no harm could be done.

So should something be done to prevent someone from writing `tink.http.Client.fetch(uri, { client: CurlCustomArgs(thisArrayComesRightFromOneOfMyUsers) })`? IIRC `tink_http` is not really supposed to be used directly.

**Comment by kevinresol** [comment]
Hmmm I think the current api already provided enough flexibility for users to use a proxy. If we want to support proxy as part of tinkhttp api that would be a much larger undertaking (i.e. not only curl)

**Comment by grepsuzette** [comment]
> Hmmm I think the current api already provided enough flexibility for users to use a proxy. If we want to support proxy as part of tinkhttp api that would be a much larger undertaking (i.e. not only curl)

I agree with reasoning.
However, I don't khow to use current API to open a proxy without opening a PR.
It looks like `Fetch.fetch()` is the one instantiating the clients, the only way I found to not rewrite `fetch()` was this PR.
Do you see another way?

**Comment by back2dos** [comment]
> It looks like `Fetch.fetch()` is the one instantiating the clients.

You can always pass `Custom(someSpecificClient)`, if that's what you're asking?

**Comment by grepsuzette** [comment]
> > It looks like `Fetch.fetch()` is the one instantiating the clients.
> 
> You can always pass `Custom(someSpecificClient)`, if that's what you're asking?

Oh okay! I was wondering what that was ^^
Well then I can close here and people who search SOCKS5 and haxe on github can find this thread,
thanks :)

**Pull request closed without merging**
