### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by benmerckx**
This is far from done, so shouldn't be merged right now. I have set this up so it compiles both server and client/runner. Compiling and running happens in neko for all tests as it doesn't need to be tested on other platforms. The tests can be run with any combination of server/client like this:

```
haxelib run travix neko -D server=NekoToolsServer -D client=NekoClient
haxelib run travix neko -D server=ModNekoServer -D client=NekoClient
haxelib run travix neko -D server=PhpServer -D client=PhpClient
haxelib run travix neko -D server=NekoServer -D client=NekoClient
haxelib run travix neko -D server=JavaServer -D client=NekoClient
haxelib run travix neko -D server=NodeServer -D client=NodeClient
haxelib run travix neko -D server=CppServer -D client=NekoClient
```

Let me know if this approach works for you and I'll polish it up and start on the actual tests as described in #33

### CODE REVIEW

**Comment by back2dos** [comment]
This is awesome. I'm not 100% sure about all the implications, but it looks like a good start and certainly a lot better than the status quo.

Personally, I think I would have compiled the client and the test into one thing, but maybe it's more flexible this way. I like it. Feel free to go ahead! ;)

**Comment by benmerckx** [comment]
Client and test are 'one thing'. But I realize the naming is confusing here as client is used to describe the platform on which the tests run and also implies which clients will connect to the server.

**Comment by benmerckx** [comment]
I've simplified compiling the servers and clients a bit. The output should become useful:
https://travis-ci.org/haxetink/tink_http/jobs/167960888#L377
I'll continue adding actual tests once https://github.com/haxetink/tink_http/issues/40 is fixed as for now all tcp containers timeout there.

**Comment by back2dos** [comment]
Uhm, can I merge it? It seems to me like an improvement over the status quo.

**Comment by benmerckx** [comment]
Sure. There's a few more things I'd like to get done but I'll send it in afterwards. Usage is like this (every available client for every target will run for each container);
haxe test.hxml -D containers=neko-tools,php,node -D targets=neko,php,node,java
It should make development easier, you can also see any traces done on the serverside.
I did not get any of the tcp clients to work, because of buddy+runloop..

**Comment by back2dos** [comment]
Alright. Thanks a lot for this!!! ;)

**Pull request merged**
