### PR TITLE
Fix nodejs stream

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by back2dos** [comment]
Well, this is unfortunate ... as Ben suggested to me, I normalized the order of name / native stream across targets in tink_io: https://github.com/haxetink/tink_io/commit/46cf298ff03486754e2407e2a98989fa6c34b4cd

You seem to be having an old verions of tink_io installed. Can you confirm that?

**Comment by kevinresol** [comment]
Indeed.

**Comment by back2dos** [comment]
Yeah, sorry about that. I'll try to do a better job at keeping you posted
on breaking changes ;)

**Comment by kevinresol** [comment]
No problem. I am aware of the API change. I just thought you forgot the update the usage.

**Pull request closed without merging**
