### PR TITLE
getAuth() from header

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by kevinresol** [comment]
Shall we have a discussion on this one?

**Comment by kevinresol** [comment]
Because we already have `contentType()` and `getCookie()` that returns readily usable information. I think we can have `getAuth()`, `getContentLength()` alike, for those common headers that require some processing before use.

**Comment by back2dos** [comment]
Generally it's a good idea. But I'd prefer to do something about the two minor issues I pointed out.

**Comment by kevinresol** [comment]
What issues are you referring to?

**Comment by back2dos** [comment]
Oh, ok, sorry ... it seems I am to stupid for GitHub reviews. I opened one for this shortly after the PR but I didn't understand that I need to submit it so that you see it also :D

**Comment by kevinresol** [comment]
ok, should be fixed now.

**Comment by kevinresol** [comment]
And I wonder if there are any invisible reviews somewhere else?

**Comment by back2dos** [comment]
> And I wonder if there are any invisible reviews somewhere else?

Bahaha. Wouldn't have thought of that :D

**Pull request merged**
