### PR TITLE
Expose server object in NodeContainer

### PR DESCRIPTION
**Pull request by kevinresol**
This is a temp solution as I need it to attach a socket.io server.

Please consider this as well when revising the Container API.

### CODE REVIEW

**Comment by back2dos** [comment]
For using tink_http in node-specific use cases, I intended [`NodeContainer.toNodeHandler`](https://github.com/haxetink/tink_http/blob/master/src/tink/http/Container.hx#L30). So you can just set up your server the way you would in node and then plug your handler written against tink_http right in there.

**Comment by kevinresol** [comment]
I see how it works now. thanks

**Comment by kevinresol** [comment]
Hm,,, I am tempted to reopen this after reading the recent update to the Containers. Because the `run` function is not as trivial as before

**Comment by back2dos** [comment]
Uhm, sure. How does that change anything though?

The `Container.run` function tries to pretend that there's one cross-platform interface that exhibits one of two behaviors. If you want to leverage nodejs-specific stuff for your transport layer, it's probably just not that useful.

You can still write your application as a `Handler` to keep it portable, and then just convert it and put it anywhere you want, e.g. into an express/connect app, or just `http.createServer(NodeContainer.toNodeHandler(theApp)).listen(2000)` or combine it with socket.io anyway you see fit.

Or could you elaborate why that's not practical?

**Comment by kevinresol** [comment]
It is not non-practical, but I would like to use Container.run because it handles the server in a "tink" way, which I prefer. On the other hand, I still need the raw node server object for other purposes, just like attaching a socket.io server and some other hacks. What I understand is that these operations don't really interfere with what tink_http is doing. So I suppose I can reuse the `run` function without implementing it again just because I want the server object.

**Comment by kevinresol** [comment]
Honestly, I am sticking to nodejs for my current project. So portability isn't really great concern to me.

To me, a uniform Container interface across platforms does attract users from different language background to use tink_http. But when one started to use it to implement his server, he will start facing some platform specific problems like I do. And there one will need to be able to access the platform-specific bits. But exposing those stuff doesn't affect the interface, because an implementation is always a superset of its interfaces.

**Comment by back2dos** [comment]
I haven't really changed my mind on this, but if you feel like it's a big gain, then please make the necessary changes and merge at your own discretion ;)

**Comment by kevinresol** [comment]
Hi, I am back (again). What if we do the thing another way round, creating another Container class that takes a httpServer instance (instead of just port number)? So we one can create and manage the server instance and do whatever they want.

**Comment by kevinresol** [comment]
Closing in favor of #73

**Pull request closed without merging**
