### PR TITLE
Added link to the documentation site

### PR DESCRIPTION
**Pull request by zicklag**
Just added a link to the documentation:page_facing_up: site in the Readme.

### CODE REVIEW

**Comment by kevinresol** [comment]
I am not sure if this is relevant, because the doc site is written for the pure branch.

**Comment by zicklag** [comment]
Oh, I didn't know that there was a pure branch. I was looking for the documentation for the library and I thought that there should be a link to it on the Github page. I still think that it would be useful. Maybe we just say that the documentation is for the pure branch and not master?

**Comment by kevinresol** [comment]
That could work

**Comment by zicklag** [comment]
Made the update.

**Comment by zicklag** [comment]
By the way, what is the `pure` branch for? Is `master` the branch I should target for PR's or should I target `pure`?

I'm going to be trying to add proxy support and I want to know what I should base it off of.

**Comment by kevinresol** [comment]
You can consider the pure branch as the "next version". So I think you can PR to there.

**Comment by kevinresol** [comment]
pure is merged back to master already

**Pull request closed without merging**
