### PR TITLE
Add Java Servlet support

### PR DESCRIPTION
**Pull request by kevinresol**
Example usage:

```haxe
package;

import tink.http.containers.JavaServlet;
import tink.http.Request;
import tink.http.Response;
using tink.CoreApi;

class Main extends JavaServlet {
	override function process(req:IncomingRequest):Future<OutgoingResponse>
		return Future.sync(('Hello, World!':OutgoingResponse));
}
```

A Servlet is not a container. It is the "contained" itself. Not sure if it fits into the container package at all. 😛 

#61

### CODE REVIEW

**Comment by back2dos** [comment]
Right now I think I'd prefer to add new containers *as needed*. If you have plans to use this, then I'm all for adding it, because it'll be an opportunity to learn from. If not, I would rather push this after 1.0.

**Comment by kevinresol** [comment]
Let's hold it then.

**Comment by kevinresol** [comment]
Just a quick background on this one:

I uses google cloud a lot and I usually use google app engine for deploying small web apps, because it is free for the standard environment. However it only supports 4 languages, namely:

- Java (using HttpServlets)
- PHP
- Python 2.7
- Go

Among the four choices, only Java and PHP is supported by Haxe and only PHP is supported by tink_http because one cannot deploy a standalone Java program there. And this is the motivation of this PR.

I have a latest small project that is still in development, which is using PHP on GAE. I will try to switch to Java Servlet and see how it works.

Anyway, I think this kind of wsgi-like handlers would be "big clients" for tink_http.

**Comment by kevinresol** [comment]
Superseded by #125

**Pull request closed without merging**
