### PR TITLE
Add SocketClient

### PR DESCRIPTION
**Pull request by kevinresol**
A client based on sys.net.Socket / sys.ssl.Socket or alike.

We only lack a FlashClient then we have the same supported targets as haxe.Http, which means we can basically abandon StdClient.

### CODE REVIEW

**Comment by back2dos** [comment]
What's the difference between this one and TcpClient?

**Comment by kevinresol** [comment]
> What's the difference between this one and TcpClient?

It does not depend on tink_tcp?

Well, actually I consider this as a strip down version of StdClient. Because at the end haxe.Http uses sys.net.sockets (except js/nodejs/flash), and I actually copied those socket codes from there. It is not only thinner, because we avoided those header conversion, etc, but also fixed the problem that haxe.Http only supports GET and POST. It may be a bonus of solving https://github.com/haxetink/tink_http/issues/67.

**Comment by kevinresol** [comment]
After merging this, I will add a FlashClient which uses flash's socket.
Then we can add a `typedef DefaultClient = ...` for each platform. e.g. js => JSClient, flash => FlashClient, others => SocketClient. By then we can basically remove StdClient altogether.

**Comment by back2dos** [comment]
Hmmm, hmm. The redundancy kind of bothers me, but let's just move along with this and see if we can maybe unify it down the line.

**Pull request merged**
